import {useEffect,useState} from 'react'
import {fmt,request} from '../api'
import './LivePaperPage.css'

type LiveState={status:string;provider:string;symbol:string;timeframe:string;connected:boolean;running:boolean;paper_only:boolean;real_orders_enabled:boolean;latest_price?:string;last_message_at?:string;last_candle_at?:string;candles_received:number;decisions_run:number;reconnects:number;last_decision?:string;last_error?:string}

export default function LivePaperPage(){
  const [state,setState]=useState<LiveState|null>(null)
  const [symbol,setSymbol]=useState('BTCUSDT')
  const [timeframe,setTimeframe]=useState('1h')
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  async function load(){try{setState(await request<LiveState>('/live-paper/status'))}catch(e){setError(e instanceof Error?e.message:String(e))}}
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),2000);return()=>window.clearInterval(timer)},[])
  async function start(){setBusy(true);setError('');try{setState(await request<LiveState>('/live-paper/start',{method:'POST',body:JSON.stringify({provider:'binance',symbol,timeframe})}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  async function stop(){setBusy(true);setError('');try{setState(await request<LiveState>('/live-paper/stop',{method:'POST'}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  const live=Boolean(state?.running)
  return <><div className="page-heading"><div><p>REAL DATA · PAPER MONEY</p><h2>Binance live paper trading</h2></div><span className={`badge ${state?.connected?'green':live?'gold':'muted'}`}>{state?.status||'LOADING'}</span></div>{error&&<div className="error">{error}</div>}<div className="live-safety"><b>No real orders can be submitted.</b> Binance supplies public market data only; QTR executes against its internal paper balance.</div><div className="metrics"><section className="card metric"><span>Live BTC price</span><strong>{state?.latest_price?fmt.money(state.latest_price):'—'}</strong><small>{state?.connected?'Binance stream connected':'Waiting for connection'}</small></section><section className="card metric"><span>Closed candles</span><strong>{state?.candles_received??0}</strong><small>Validated and persisted</small></section><section className="card metric"><span>Decisions run</span><strong>{state?.decisions_run??0}</strong><small>Last: {state?.last_decision||'—'}</small></section><section className="card metric"><span>Reconnects</span><strong>{state?.reconnects??0}</strong><small>Automatic backoff</small></section></div><div className="grid two"><section className="card"><header><span>SESSION CONTROL</span><h3>Public market feed</h3></header><div className="form-grid"><label className="field"><span>Symbol</span><input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} disabled={live}/></label><label className="field"><span>Timeframe</span><select value={timeframe} onChange={e=>setTimeframe(e.target.value)} disabled={live}><option value="1m">1 minute</option><option value="5m">5 minutes</option><option value="15m">15 minutes</option><option value="1h">1 hour</option><option value="4h">4 hours</option><option value="1d">1 day</option></select></label></div>{live?<button className="secondary" onClick={stop} disabled={busy}>Stop live paper</button>:<button className="primary" onClick={start} disabled={busy}>{busy?'Starting…':'Start Binance live paper'}</button>}<p className="fine">The active strategy must use the same symbol and timeframe. Decisions run only on closed candles; stops and targets are monitored from live price updates.</p></section><section className="card"><header><span>CONNECTION</span><h3>Operational state</h3></header><div className="status-list"><p><span>Provider</span><b>{state?.provider||'binance'}</b></p><p><span>Market</span><b>{state?.symbol||symbol} · {state?.timeframe||timeframe}</b></p><p><span>Last message</span><b>{fmt.date(state?.last_message_at)}</b></p><p><span>Last closed candle</span><b>{fmt.date(state?.last_candle_at)}</b></p><p><span>Execution</span><b className="safe-text">PAPER ONLY</b></p></div>{state?.last_error&&<div className="error">{state.last_error}</div>}</section></div></>
}
